### PR TITLE
docs, skip ITs on deploy

### PR DESCRIPTION
**Pull request by h1alexbel**
## PR-Codex overview
This PR focuses on updating the Maven command in the `.rultor.yml` file and modifying the code in the `README.md` file to include a new parameter in the `Preload` constructor.

### Detailed summary
- Updated Maven command in `.rultor.yml` to include the `-DskipITs` flag.
- Modified code in `README.md` to include a new parameter in the `Preload` constructor.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-08-25T09:09:08.799406``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@zoeself derigester

**Comment by zoeself** [comment]
> @zoeself derigester

@h1alexbel didn't understand that, sorry.

**Comment by h1alexbel** [comment]
@zoeself deregister

**Comment by zoeself** [comment]
> @zoeself deregister

@h1alexbel ok, I've removed this task from scope. I'm not managing it anymore.

**Pull request merged**
