### PR TITLE
text blocks with jtcop `1.1.1`

### LINKED ISSUE #39: migrate to `JTCOP 1.1.1`
since text blocks are [supported](https://github.com/volodya-lombrozo/jtcop/issues/262), we should migrate to JTCOP `1.1.1` version that work with it

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #39 

---

## PR-Codex overview
This PR focuses on updating dependencies and formatting code in the `pom.xml` file and `StateChangesTest.java`. 

### Detailed summary
- Updated `jtcop.version` in `pom.xml` from `0.1.14` to `1.1.1`.
- Updated `slf4j.version` in `pom.xml` from `2.0.7` to `1.6.13`.
- Updated `checkstyle.version` in `pom.xml` from `8.15` to `3.3.0`.
- Added formatted code for creating keyspace and table in `StateChangesTest.java`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-08-17T09:59:09.806959``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
