### PR TITLE
README

### LINKED ISSUE #7: readme

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #7 

---

## PR-Codex overview
This PR updates the project description and adds several badges and information to the README.md file.

### Detailed summary
- Updated the project description in the `pom.xml` file.
- Added several badges and information to the `README.md` file:
  - Self XDSD badge.
  - EO principles badge.
  - DevOps by Rultor.com badge.
  - IntelliJ IDEA recommendation badge.
  - Maven workflow badge.
  - Maven Central badge.
  - Javadoc badge.
  - Codecov badge.
  - Hits-of-Code badge.
  - Lines-of-Code badge.
  - PDD status badge.
  - License badge.
- Added project architect information.
- Added motivation section.
- Added principles section.
- Added "How to use" section with Maven dependency information.
- Added "How to Contribute" section with instructions for contributing to the project.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-08-13T11:09:16.279289``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@rultor merte

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
