### PR TITLE
testcontainers setup

### LINKED ISSUE #26: testcontainers setup

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #26

@l3r8yJ take a look, please

---

## PR-Codex overview
This PR focuses on improving the Maven build process and adding integration tests for the Cassandra session. 

### Detailed summary
- Updated the Maven build command to skip integration tests.
- Added integration tests for the Cassandra session.
- Updated the GitHub Actions workflow to include integration tests.
- Added dependencies for Hamcrest, Mockito, and Testcontainers.
- Added a new test class for running Cassandra in integration tests.

> The following files were skipped due to too many changes: `src/test/java/it/CassandraIntegration.java`, `src/test/java/io/github/eocqrs/cmig/session/SimpleTest.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-08-17T11:49:05.597190``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@l3r8yJ WDYT?

**Review by l3r8yJ — APPROVED** [review]
@h1alexbel looks good to me!

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@h1alexbel I'm not sure if we can merge this pr with #43, because that one doesn't work on my mac either

**Comment by h1alexbel** [comment]
@l3r8yJ need to deep dive into SHA256 algorithm then

**Comment by h1alexbel** [comment]
@l3r8yJ rultor reads config from the master branch, where the build is running with ITs;
seems that SHA works on multiple machines (CI/rultor)

**Comment by l3r8yJ** [comment]
@h1alexbel i think it is gonna be ok after i close #43

**Comment by h1alexbel** [comment]
@l3r8yJ OK, waiting for #43

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@h1alexbel you need to add `skip it` for `.rultor` to master before this will merge

**Comment by h1alexbel** [comment]
@l3r8yJ created #45

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
